# Permalinks
permalink:           pretty

# Show postdated posts
future:           false

# Setup
title:               Statistics for the Confused
tagline:             ''
description:         'Statistics for the Confused'
url:                 https://hueywoonlee.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Huey Woon Lee
  url:               ''
  email:             leehueywoon@gmail.com

# Custom vars
version:             1.0.0
