# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Statistics Resources
tagline:             'Statistics for the confused'
description:         'Statistics for the confused'
url:                 https://hueywoonlee.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Huey Woon Lee
  url:               ''
  email:             leehueywoon@gmail.com

# Custom vars
version:             1.0.0
